/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calmirea;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

  
/**
 *
 * @author qilah filzah
 */
public class HalamanPengembalian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HalamanPengembalian.class.getName());
    
    /**
     * Creates new form HalamanPengembalianBuku
     */
    
   public HalamanPengembalian() {
    initComponents();

    tampilTanggalOtomatis();
    bersihkanDetail();
}
   
    private void tampilTanggalOtomatis() {
    try {
        java.text.SimpleDateFormat sdfInput =
                new java.text.SimpleDateFormat("yyyy-MM-dd");
        jTextField1.setText(sdfInput.format(new java.util.Date()));
    } catch (Exception e) {
        jTextField1.setText("yyyy-MM-dd");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        latarGradasi1 = new calmirea.LatarGradasi();
        KondisiBuku = new javax.swing.JComboBox<>();
        kembaliBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nmpeminjamLB = new javax.swing.JLabel();
        judulbukuLB = new javax.swing.JLabel();
        lamapinjamLB = new javax.swing.JLabel();
        jatuhtempoLB = new javax.swing.JLabel();
        tglkembaliLB = new javax.swing.JLabel();
        dendaLB = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        kembalikanBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KondisiBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak ", "Hilang" }));
        KondisiBuku.addActionListener(this::KondisiBukuActionPerformed);

        kembaliBT.setText("Kembali");
        kembaliBT.addActionListener(this::kembaliBTActionPerformed);

        jLabel1.setText("ID Pinjam");

        jTextField1.setText("dd/mm/yy");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel2.setText("Tanggal Kembali");

        jLabel3.setText("Kondisi Buku");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Pengembalian ");

        jTextField2.setText("masukkan id");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pengembalian")));

        jLabel5.setText("Nama Peminjam");

        jLabel6.setText("Judul Buku");

        jLabel7.setText("Lama Pinjam");

        jLabel8.setText("Jatuh Tempo");

        jLabel9.setText("Tgl Kembali");

        jLabel21.setText("Denda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lamapinjamLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(judulbukuLB, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dendaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tglkembaliLB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jatuhtempoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nmpeminjamLB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(nmpeminjamLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(judulbukuLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(lamapinjamLB, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jatuhtempoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglkembaliLB, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(dendaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        kembalikanBT.setText("Kembalikan");
        kembalikanBT.addActionListener(this::kembalikanBTActionPerformed);

        javax.swing.GroupLayout latarGradasi1Layout = new javax.swing.GroupLayout(latarGradasi1);
        latarGradasi1.setLayout(latarGradasi1Layout);
        latarGradasi1Layout.setHorizontalGroup(
            latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latarGradasi1Layout.createSequentialGroup()
                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(latarGradasi1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(latarGradasi1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(latarGradasi1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kembalikanBT)
                            .addGroup(latarGradasi1Layout.createSequentialGroup()
                                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KondisiBuku, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jTextField2))))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, latarGradasi1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kembaliBT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        latarGradasi1Layout.setVerticalGroup(
            latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latarGradasi1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KondisiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(kembalikanBT)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(kembaliBT)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(latarGradasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(latarGradasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KondisiBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KondisiBukuActionPerformed
    String idPinjam = jTextField2.getText().trim();

    if (!idPinjam.isEmpty() && !idPinjam.equals("masukkan id")) {
        try {
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/calmirea",
                "root",
                ""
            );

            String sql = "SELECT * FROM peminjaman WHERE id_pinjam = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idPinjam);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                hitungDendaOtomatis(
                    rs.getString("tanggal_pinjam"),
                    rs.getString("tanggal_kembali")
                );
            }

            conn.close();

        } catch (Exception e) {
            // Ignore
        }
    }
    }//GEN-LAST:event_KondisiBukuActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
      kembalikanBTActionPerformed(evt);
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void kembaliBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTActionPerformed
        new menuUtama().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_kembaliBTActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void kembalikanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikanBTActionPerformed
                                            
    String idPinjam = jTextField2.getText().trim();

    
    if (idPinjam.isEmpty() || idPinjam.equals("masukkan id")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silahkan masukkan ID Pinjam terlebih dahulu!");
        return;
    }

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/calmirea", "root", "");
        
        
       String sql = "SELECT p.*, b.judul " +
             "FROM peminjaman p " +
             "JOIN buku b ON p.id_buku = b.id_buku " +
             "WHERE p.id_pinjam = ?";
        
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idPinjam);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            String status = rs.getString("status");
            
            System.out.println("ID Pinjam : " + idPinjam);
            System.out.println("Tanggal Pinjam : " + rs.getString("tanggal_pinjam"));
            System.out.println("Jatuh Tempo : " + rs.getString("tanggal_kembali"));
            System.out.println("Tanggal Hari Ini : " + jTextField1.getText());

            nmpeminjamLB.setText(rs.getString("nama_peminjam"));
            judulbukuLB.setText(rs.getString("judul"));         
            
            String tglJatuhTempo = rs.getString("tanggal_kembali"); 
            jatuhtempoLB.setText(tglJatuhTempo);
            
            String tglHariIni = jTextField1.getText();
            tglkembaliLB.setText(tglHariIni);
            
            hitungDendaOtomatis(rs.getString("tanggal_pinjam"), tglJatuhTempo);
            
            if ("Dikembalikan".equalsIgnoreCase(status) || "Kembali".equalsIgnoreCase(status)) {
               
                javax.swing.JOptionPane.showMessageDialog(this, "Buku dengan ID Pinjam ini sudah dikembalikan!");
            } else {
              
               System.out.println("Isi dendaLB : " + dendaLB.getText());
               
               

              String dendaTeks = dendaLB.getText().replace("Rp ", "").trim();
              System.out.println("Denda yang akan disimpan : " + dendaTeks);

               long totalDenda = Long.parseLong(dendaTeks);                
               String kondisi = KondisiBuku.getSelectedItem().toString().trim();
                
                String sqlUpdate = "UPDATE peminjaman SET status = 'Dikembalikan', kondisi_buku = ?, denda = ? WHERE id_pinjam = ?";
                PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
                pstUpdate.setString(1, kondisi);
                pstUpdate.setLong(2, totalDenda);
                pstUpdate.setString(3, idPinjam);
                pstUpdate.executeUpdate();
                
                String sqlStok = "UPDATE buku SET stok = stok + 1 WHERE id_buku = ?";
                PreparedStatement pstStok = conn.prepareStatement(sqlStok);
                pstStok.setString(1, rs.getString("id_buku"));
                pstStok.executeUpdate();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Ditemukan & Status Berhasil Diperbarui!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID Pinjam tidak ditemukan!");
            bersihkanDetail();
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan database: " + e.getMessage());
    }
    }                                            

  private void hitungDendaOtomatis(String tglPinjamStr, String tglJatuhTempoStr) {
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String tglKembaliStr = jTextField1.getText();

        if (tglKembaliStr.equals("yyyy-MM-dd") || tglKembaliStr.isEmpty()) {
            dendaLB.setText("Rp 0");
            return;
        }

        Date tglPinjam = sdf.parse(tglPinjamStr);
        Date tglJatuhTempo = sdf.parse(tglJatuhTempoStr);
        Date tglKembali = sdf.parse(tglKembaliStr);

        // Lama pinjam
        long selisihPinjam = tglKembali.getTime() - tglPinjam.getTime();
        long lamaHari = selisihPinjam / (1000 * 60 * 60 * 24);
        if (lamaHari < 0) lamaHari = 0;
        lamapinjamLB.setText(lamaHari + " Hari");

        // Denda keterlambatan
        long denda = 0;
        if (tglKembali.after(tglJatuhTempo)) {
            long telat = (tglKembali.getTime() - tglJatuhTempo.getTime())
                       / (1000 * 60 * 60 * 24);
            denda = telat * 1000;
        }

        // Denda kondisi buku
        String kondisi = KondisiBuku.getSelectedItem().toString().trim();
        if (kondisi.equalsIgnoreCase("Rusak")) {
            denda += 20000;
        } else if (kondisi.equalsIgnoreCase("Hilang")) {
            denda += 100000;
        }

        dendaLB.setText("Rp " + denda);

    } catch (Exception e) {
        lamapinjamLB.setText("-");
        dendaLB.setText("Rp 0");
        e.printStackTrace(); // supaya kalau error kelihatan penyebabnya
    }
    }//GEN-LAST:event_kembalikanBTActionPerformed
  
    
    private void bersihkanDetail() {
      nmpeminjamLB.setText("-");
        judulbukuLB.setText("-");
        lamapinjamLB.setText("-");
        jatuhtempoLB.setText("-");
        tglkembaliLB.setText("-");
        dendaLB.setText("Rp 0");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new HalamanPengembalian().setVisible(true);
    }
});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> KondisiBuku;
    private javax.swing.JLabel dendaLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jatuhtempoLB;
    private javax.swing.JLabel judulbukuLB;
    private javax.swing.JButton kembaliBT;
    private javax.swing.JButton kembalikanBT;
    private javax.swing.JLabel lamapinjamLB;
    private calmirea.LatarGradasi latarGradasi1;
    private javax.swing.JLabel nmpeminjamLB;
    private javax.swing.JLabel tglkembaliLB;
    // End of variables declaration//GEN-END:variables


}
