/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calmirea;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class MenuUtamaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName());

    /**
     * Creates new form MenuUtamaUser
     */
    public MenuUtamaAdmin() {
        initComponents();
        setupMouseEvents();
        this.setResizable(false);
        this.setSize(705, 640); 
        this.setLocationRelativeTo(null);
    }
    
    public MenuUtamaAdmin(String username) {
        initComponents();
        setupMouseEvents();
        this.setResizable(false);
        
        latarGradasi1.setPreferredSize(new java.awt.Dimension(710, 640));
        latarGradasi1.setMinimumSize(new java.awt.Dimension(710, 640));

        this.pack(); 
        this.setLocationRelativeTo(null);
        
        jLabel2.setText("Hi, " + username + "!");
    }

    private void setupMouseEvents() {
        picdatabuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));         // Ikon Data Buku
        picdatauser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));      // Ikon Data User
        piclaporanbuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));   // Ikon Laporan Buku
        PanelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));     // Kotak Panel Logout

        picdatabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        picdatauser.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picdatauserMouseClicked(evt);
            }
        });
        piclaporanbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piclaporanbukuMouseClicked(evt);
            }
        });
        PanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelLogoutMouseClicked(evt);
            }
        });
    }

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) { 
        new HalamanDataBuku().setVisible(true);
        this.dispose();
    }
   private void picdatauserMouseClicked(java.awt.event.MouseEvent evt) { 
        new HalamanDataUser().setVisible(true);
        this.dispose();
   }
    
    private void piclaporanbukuMouseClicked(java.awt.event.MouseEvent evt) { 
        new HalamanLaporanBuku().setVisible(true);
        this.dispose();
    }

    private void PanelLogoutMouseClicked(java.awt.event.MouseEvent evt) {
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin keluar?", "Logout", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            new HalamanLogin().setVisible(true);
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        latarGradasi1 = new calmirea.LatarGradasi();
        calmireaLbl = new javax.swing.JLabel();
        panelBesar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        picdatabuku = new javax.swing.JLabel();
        picdatauser = new javax.swing.JLabel();
        piclaporanbuku = new javax.swing.JLabel();
        PanelLogout = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        latarGradasi1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        latarGradasi1.setPreferredSize(new java.awt.Dimension(710, 640));

        calmireaLbl.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        calmireaLbl.setForeground(new java.awt.Color(138, 28, 50));
        calmireaLbl.setText("Calmirea'd Library");

        panelBesar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(138, 28, 50));
        jLabel4.setText("Data Buku");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(138, 28, 50));
        jLabel8.setText("Laporan Buku");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(138, 28, 50));
        jLabel10.setText("Data User");

        picdatabuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Book.png"))); // NOI18N

        picdatauser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (9) (2) (2).png"))); // NOI18N

        piclaporanbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (8) (1) (3).png"))); // NOI18N

        javax.swing.GroupLayout panelBesarLayout = new javax.swing.GroupLayout(panelBesar);
        panelBesar.setLayout(panelBesarLayout);
        panelBesarLayout.setHorizontalGroup(
            panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBesarLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picdatabuku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(picdatauser, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBesarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(50, 50, 50))
                    .addGroup(panelBesarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(piclaporanbuku)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelBesarLayout.setVerticalGroup(
            panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBesarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBesarLayout.createSequentialGroup()
                        .addComponent(picdatabuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(panelBesarLayout.createSequentialGroup()
                        .addGroup(panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBesarLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(piclaporanbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBesarLayout.createSequentialGroup()
                                .addComponent(picdatauser, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGroup(panelBesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        PanelLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(138, 28, 50));
        jLabel12.setText("Logout");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (1) (3).png"))); // NOI18N

        javax.swing.GroupLayout PanelLogoutLayout = new javax.swing.GroupLayout(PanelLogout);
        PanelLogout.setLayout(PanelLogoutLayout);
        PanelLogoutLayout.setHorizontalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(28, 28, 28))
        );
        PanelLogoutLayout.setVerticalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 28, 50));
        jLabel2.setText("Hi, Admin!");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (7) (1) (1).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calmirea/Logo (1) (1).png"))); // NOI18N

        javax.swing.GroupLayout latarGradasi1Layout = new javax.swing.GroupLayout(latarGradasi1);
        latarGradasi1.setLayout(latarGradasi1Layout);
        latarGradasi1Layout.setHorizontalGroup(
            latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latarGradasi1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(545, 545, 545)
                .addComponent(jLabel2)
                .addGap(79, 79, 79))
            .addGroup(latarGradasi1Layout.createSequentialGroup()
                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(latarGradasi1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(calmireaLbl)))
                    .addGroup(latarGradasi1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(panelBesar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(latarGradasi1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(PanelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        latarGradasi1Layout.setVerticalGroup(
            latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latarGradasi1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(latarGradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calmireaLbl)
                .addGap(18, 18, 18)
                .addComponent(panelBesar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(latarGradasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(latarGradasi1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtamaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogout;
    private javax.swing.JLabel calmireaLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private calmirea.LatarGradasi latarGradasi1;
    private javax.swing.JPanel panelBesar;
    private javax.swing.JLabel picdatabuku;
    private javax.swing.JLabel picdatauser;
    private javax.swing.JLabel piclaporanbuku;
    // End of variables declaration//GEN-END:variables

}