/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calmirea;
/**
 *
 * @author Sri Dayanti
 */

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.ImageIcon;
import java.awt.Image;
import calmirea.LatarGradasi;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class Peminjaman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Peminjaman.class.getName());
    
    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
    initComponents();
    
    tampilTanggal();
    isiComboBuku(); // Memuat data buku
    loadTabel();    // Memuat tabel peminjaman

    tampilGambar();
    tengahKolomNo(); 
}
  
    
   private void tengahKolomNo() {

    // isi data kolom No ke tengah
    DefaultTableCellRenderer center =
            new DefaultTableCellRenderer();

    center.setHorizontalAlignment(
            javax.swing.SwingConstants.CENTER
    );

    peminjamanTB.getColumnModel()
            .getColumn(0)
            .setCellRenderer(center);

    // header "No" ke tengah
    ((javax.swing.table.DefaultTableCellRenderer)
            peminjamanTB.getTableHeader()
            .getDefaultRenderer())
            .setHorizontalAlignment(
                    javax.swing.JLabel.CENTER
            );
}
    
    private void tampilGambar() {

    java.net.URL url =
            getClass().getResource("/images/BukuPeminjaman.png");

    if (url == null) {
        System.out.println("Gambar tidak ditemukan!");
        return;
    }

    ImageIcon icon = new ImageIcon(url);

    Image img = icon.getImage().getScaledInstance(
            180,
            180,
            Image.SCALE_SMOOTH
    );

    jLabel1.setIcon(new ImageIcon(img));
}
    
    private void isiComboPeminjam() {

}
    
    private void isiComboBuku() {
try {
        java.sql.Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT id_buku FROM buku"; 
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        
        idbukuCMB.removeAllItems();
        idbukuCMB.addItem("- Pilih ID Buku -");
        
        while(rs.next()) {
            idbukuCMB.addItem(rs.getString("id_buku"));
        }
    } catch (Exception e) {
        System.out.println("Gagal mengisi combo ID Buku: " + e.getMessage());
    }
}
   
    private void loadTabel() {
        DefaultTableModel model = (DefaultTableModel) peminjamanTB.getModel();
        model.setRowCount(0); // Bersihkan isi tabel sebelum memuat data baru

        try {
            java.sql.Connection conn = Koneksi.getKoneksi(); 
            java.sql.Statement stm = conn.createStatement();
            
            // KITA CUMA JOIN KE TABEL BUKU UTK MENGAMBIL JUDUL
            // Karena nama_lengkap sudah ada di tabel peminjaman Kakak
            String sql = "SELECT p.*, u.nama_lengkap, b.judul " +
                         "FROM peminjaman p " +
                         "JOIN user u ON p.id_user = u.id_user " +
                         "JOIN buku b ON p.id_buku = b.id_buku";
                         
            java.sql.ResultSet rs = stm.executeQuery(sql);
            
            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getString("nama_lengkap"),
                    rs.getString("id_buku"),
                    rs.getString("judul"),         // Diambil dari tabel buku lewat JOIN di atas
                    rs.getString("tanggal_pinjam"),
                    rs.getString("tanggal_kembali"),
                    rs.getString("status")
                });
            }
            
            totaldataTF.setText(String.valueOf(model.getRowCount()));
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Gagal Load Tabel: " + e.getMessage());
        e.printStackTrace();
        }
} 

    private void tampilTanggal() {
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    tanggalTF.setText(sdf.format(new Date()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new LatarGradasi();
        judulLB = new javax.swing.JLabel();
        perpustakaanLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datapeminjamLB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namapeminjamTF = new javax.swing.JTextField();
        nomorteleponTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        judulbukuTF = new javax.swing.JTextField();
        penulisTF = new javax.swing.JTextField();
        kategoriTF = new javax.swing.JTextField();
        stokTF = new javax.swing.JTextField();
        idbukuCMB = new javax.swing.JComboBox<>();
        cariBT = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tglpinjamTF = new javax.swing.JTextField();
        keteranganTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tglkembaliTF = new javax.swing.JTextField();
        simpanBT = new javax.swing.JButton();
        resetBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();
        cetakBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        peminjamanTB = new javax.swing.JTable();
        kembaliBT = new javax.swing.JButton();
        tanggalTF = new javax.swing.JTextField();
        totaldataLB = new javax.swing.JLabel();
        totaldataTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        alamatTF1 = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulLB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        judulLB.setText("PEMINJAMAN BUKU - USER");

        perpustakaanLB.setText("Perpustakaan");

        jLabel3.setText("Tanggal  :");

        datapeminjamLB.setText("DATA PEMINJAM");

        jLabel5.setText("ID Peminjam          :");

        jLabel6.setText("Nama Pemiinjam   :");

        jLabel7.setText("No. Telepon           :");

        jLabel8.setText("Alamat                   :");

        namapeminjamTF.addActionListener(this::namapeminjamTFActionPerformed);

        nomorteleponTF.addActionListener(this::nomorteleponTFActionPerformed);

        alamatTF.addActionListener(this::alamatTFActionPerformed);

        jLabel9.setText("DATA BUKU");

        jLabel10.setText("ID Buku          :");

        jLabel11.setText("Judul Buku     :");

        jLabel12.setText("Penulis           :");

        jLabel13.setText("Kategori        :   ");

        jLabel14.setText("Stok               :");

        judulbukuTF.addActionListener(this::judulbukuTFActionPerformed);

        penulisTF.addActionListener(this::penulisTFActionPerformed);

        kategoriTF.addActionListener(this::kategoriTFActionPerformed);

        stokTF.addActionListener(this::stokTFActionPerformed);

        idbukuCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idbukuCMB.addActionListener(this::idbukuCMBActionPerformed);

        cariBT.setBackground(new java.awt.Color(255, 102, 102));
        cariBT.setText("Cari");
        cariBT.addActionListener(this::cariBTActionPerformed);

        jLabel18.setText("Tanggal Pinjam    :");

        jLabel19.setText("Keterangan           :");

        tglpinjamTF.addActionListener(this::tglpinjamTFActionPerformed);

        keteranganTF.addActionListener(this::keteranganTFActionPerformed);

        jLabel20.setText("Tanggal Kembali     :");

        tglkembaliTF.addActionListener(this::tglkembaliTFActionPerformed);

        simpanBT.setBackground(new java.awt.Color(255, 102, 102));
        simpanBT.setText("Simpan");
        simpanBT.addActionListener(this::simpanBTActionPerformed);

        resetBT.setBackground(new java.awt.Color(255, 102, 102));
        resetBT.setText("Reset");
        resetBT.addActionListener(this::resetBTActionPerformed);

        editBT.setBackground(new java.awt.Color(255, 102, 102));
        editBT.setText("Edit");
        editBT.addActionListener(this::editBTActionPerformed);

        hapusBT.setBackground(new java.awt.Color(255, 102, 102));
        hapusBT.setText("Hapus");
        hapusBT.addActionListener(this::hapusBTActionPerformed);

        cetakBT.setBackground(new java.awt.Color(255, 102, 102));
        cetakBT.setText("Cetak");
        cetakBT.addActionListener(this::cetakBTActionPerformed);

        peminjamanTB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        peminjamanTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Peminjam", "ID Buku", "Judul Buku", "Tgl Pinjam", "Tgl Kembali", "Status"
            }
        ));
        jScrollPane1.setViewportView(peminjamanTB);

        kembaliBT.setText("Kembali");
        kembaliBT.addActionListener(this::kembaliBTActionPerformed);

        tanggalTF.setBackground(new java.awt.Color(255, 102, 102));
        tanggalTF.addActionListener(this::tanggalTFActionPerformed);

        totaldataLB.setText("Total Data :");

        totaldataTF.addActionListener(this::totaldataTFActionPerformed);

        alamatTF1.addActionListener(this::alamatTF1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datapeminjamLB)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namapeminjamTF, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(alamatTF)
                            .addComponent(nomorteleponTF)
                            .addComponent(alamatTF1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kategoriTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penulisTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulbukuTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(idbukuCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cariBT))
                            .addComponent(stokTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perpustakaanLB)
                .addGap(282, 282, 282)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(kembaliBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totaldataLB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totaldataTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(simpanBT)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tglpinjamTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tglkembaliTF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addComponent(keteranganTF, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(resetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(editBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(hapusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(cetakBT))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(judulLB, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(judulLB)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(perpustakaanLB)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datapeminjamLB)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(idbukuCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariBT)
                            .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(namapeminjamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(judulbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nomorteleponTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(penulisTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(kategoriTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alamatTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(stokTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglpinjamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tglkembaliTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(keteranganTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBT)
                    .addComponent(resetBT)
                    .addComponent(editBT)
                    .addComponent(hapusBT)
                    .addComponent(cetakBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaldataLB)
                    .addComponent(totaldataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembaliBT))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglkembaliTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglkembaliTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkembaliTFActionPerformed

    private void kembaliBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTActionPerformed
        new menuUtama().setVisible(true);
        kembaliBT.setBackground(new java.awt.Color(108,117,125));
        kembaliBT.setForeground(java.awt.Color.WHITE);

        this.dispose();
    }//GEN-LAST:event_kembaliBTActionPerformed

    private void tanggalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalTFActionPerformed

    private void namapeminjamTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapeminjamTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapeminjamTFActionPerformed

    private void alamatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatTFActionPerformed

    private void penulisTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penulisTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penulisTFActionPerformed

    private void kategoriTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriTFActionPerformed

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed

        // 1. Tampung dulu semua isian dari layar
        String idBuku = idbukuCMB.getSelectedItem().toString();
        String namaPeminjam = namapeminjamTF.getText(); 
        String judul = judulbukuTF.getText();
        String tglPinjam = tglpinjamTF.getText();
        String tglKembali = tglkembaliTF.getText();
        String status = "Dipinjam";
        
        // Kondisi buku dan denda dikosongkan saat pertama kali pinjam
        String kondisiBuku = "-"; 
        String denda = "0";

        try {
            java.sql.Connection conn = Koneksi.getKoneksi();
            
            // 2. Sesuaikan ejaan kolom dengan yang ada di gambar database Kakak
            // Perhatikan kolom ke-3 adalah "judul" (bukan "judul_buku")
            String sql = "INSERT INTO peminjaman (nama_peminjam, id_buku, tanggal_pinjam, tanggal_kembali, status, kondisi_buku, denda) "
           + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            
           java.sql.PreparedStatement pst = conn.prepareStatement(sql);

             pst.setString(1, namaPeminjam); // dari textfield nama peminjam
             pst.setString(2, idBuku);
             pst.setString(3, tglPinjam);
             pst.setString(4, tglKembali);
             pst.setString(5, status);
             pst.setString(6, kondisiBuku);
             pst.setString(7, denda);

             pst.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Mantap! Data resmi masuk ke Database!");

            // 4. Update tabel di layar
            DefaultTableModel model = (DefaultTableModel) peminjamanTB.getModel();
            model.addRow(new Object[]{
                model.getRowCount() + 1,
                namaPeminjam,
                idBuku,
                judul,
                tglPinjam,
                tglKembali,
                status
            });

            totaldataTF.setText(String.valueOf(model.getRowCount()));

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Oops Gagal Simpan: " + e.getMessage());
        }
 
   
    }//GEN-LAST:event_simpanBTActionPerformed

    private void cetakBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBTActionPerformed
        try{
        peminjamanTB.print();
    }catch(Exception e){
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_cetakBTActionPerformed

    private void nomorteleponTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorteleponTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorteleponTFActionPerformed

    private void idbukuCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbukuCMBActionPerformed
                                                                  
    String idTerpilih = idbukuCMB.getSelectedItem() != null ? idbukuCMB.getSelectedItem().toString() : "";
    
    if (!idTerpilih.isEmpty() && !idTerpilih.equals("- Pilih ID Buku -") && !idTerpilih.equals("Item 1")) {
        try {
            // Menggunakan jalur koneksi database project kamu
            java.sql.Connection conn = Koneksi.getKoneksi(); 
            String sql = "SELECT judul, penulis, penerbit, stok FROM buku WHERE id_buku = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idTerpilih);
            java.sql.ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                // Semua data buku langsung otomatis disuntikkan ke kolom teks masing-masing
                judulbukuTF.setText(rs.getString("judul"));
                penulisTF.setText(rs.getString("penulis"));
                kategoriTF.setText(rs.getString("penerbit")); // mengambil data dari kolom penerbit database
                stokTF.setText(rs.getString("stok"));
            }
        } catch (Exception e) {
            System.out.println("Gagal memuat detail buku: " + e.getMessage());
        }
    } else {
        // Kosongkan form jika default yang terpilih
        judulbukuTF.setText("");
        penulisTF.setText("");
        kategoriTF.setText("");
        stokTF.setText("");
    }

    }//GEN-LAST:event_idbukuCMBActionPerformed

    private void cariBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBTActionPerformed
                                     
    // Mengambil ID Buku dari kolom inputan (Asumsi namanya sesuai komponen yang tertera di kode: idbukuCMB)
    String idTerpilih = idbukuCMB.getSelectedItem() != null ? idbukuCMB.getSelectedItem().toString() : "";
    
    if (idTerpilih.isEmpty() || idTerpilih.equals("- Pilih ID Buku -")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan masukkan atau pilih ID Buku terlebih dahulu!");
        return;
    }

    try {
        java.sql.Connection conn = KoneksiDataUser.getKoneksi();
        String sql = "SELECT judul, penulis, penerbit, stok FROM buku WHERE id_buku = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idTerpilih);
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            // Berhasil Menemukan Buku, Teks Otomatis Terisi!
            judulbukuTF.setText(rs.getString("judul"));
            penulisTF.setText(rs.getString("penulis"));
            kategoriTF.setText(rs.getString("penerbit")); 
            stokTF.setText(rs.getString("stok"));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID Buku tidak ditemukan di database!");
        }
    } catch (Exception e) {
        System.out.println("Gagal mengambil detail buku: " + e.getMessage());
    }
    }//GEN-LAST:event_cariBTActionPerformed

    private void stokTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokTFActionPerformed

    private void judulbukuTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulbukuTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulbukuTFActionPerformed

    private void tglpinjamTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpinjamTFActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    tglpinjamTF.setText(sdf.format(new Date()));
    }//GEN-LAST:event_tglpinjamTFActionPerformed

    private void keteranganTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keteranganTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keteranganTFActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
         int row = peminjamanTB.getSelectedRow();

    if(row >= 0){

        DefaultTableModel model =
                (DefaultTableModel) peminjamanTB.getModel();

       
        model.setValueAt(namapeminjamTF.getText(), row, 3);
        model.setValueAt(idbukuCMB.getSelectedItem(), row, 4);
        model.setValueAt(judulbukuTF.getText(), row, 5);
        model.setValueAt(tglpinjamTF.getText(), row, 6);
        model.setValueAt(tglkembaliTF.getText(), row, 7);
    }
    }//GEN-LAST:event_editBTActionPerformed

    private void resetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTActionPerformed
        namapeminjamTF.setText("");
    nomorteleponTF.setText("");
    alamatTF.setText("");

    judulbukuTF.setText("");
    penulisTF.setText("");
    kategoriTF.setText("");
    stokTF.setText("");

    tglpinjamTF.setText("");
    tglkembaliTF.setText("");
    keteranganTF.setText("");
    }//GEN-LAST:event_resetBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        DefaultTableModel model =
            (DefaultTableModel) peminjamanTB.getModel();

    int row = peminjamanTB.getSelectedRow();

    if (row >= 0) {
        model.removeRow(row);

        totaldataTF.setText(
                String.valueOf(model.getRowCount())
        );
    }
    }//GEN-LAST:event_hapusBTActionPerformed

    private void totaldataTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldataTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaldataTFActionPerformed

    private void alamatTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatTF1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(
                        info.getClassName()
                );
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(
                Peminjaman.class.getName()
        ).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
            new Peminjaman().setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTF;
    private javax.swing.JTextField alamatTF1;
    private javax.swing.JButton cariBT;
    private javax.swing.JButton cetakBT;
    private javax.swing.JLabel datapeminjamLB;
    private javax.swing.JButton editBT;
    private javax.swing.JButton hapusBT;
    private javax.swing.JComboBox<String> idbukuCMB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulLB;
    private javax.swing.JTextField judulbukuTF;
    private javax.swing.JTextField kategoriTF;
    private javax.swing.JButton kembaliBT;
    private javax.swing.JTextField keteranganTF;
    private javax.swing.JTextField namapeminjamTF;
    private javax.swing.JTextField nomorteleponTF;
    private javax.swing.JTable peminjamanTB;
    private javax.swing.JTextField penulisTF;
    private javax.swing.JLabel perpustakaanLB;
    private javax.swing.JButton resetBT;
    private javax.swing.JButton simpanBT;
    private javax.swing.JTextField stokTF;
    private javax.swing.JTextField tanggalTF;
    private javax.swing.JTextField tglkembaliTF;
    private javax.swing.JTextField tglpinjamTF;
    private javax.swing.JLabel totaldataLB;
    private javax.swing.JTextField totaldataTF;
    // End of variables declaration//GEN-END:variables
}